name: Climate Schedule
slug: climate_schedule
description: Manage climate schedules with a dedicated UI.
version: 0.1.21
arch:
  - amd64
  - aarch64
  - armv7
startup: services
init: false
panel_title: Heizung
panel_icon: mdi:home-thermometer
panel_admin: false
ingress: true
ingress_port: 3001
homeassistant_api: true
options: {}
schema:
  mqtt_url: str
  mqtt_username: str
  mqtt_password: password
